if: tag IS blank

language: node_js

node_js:
  - "lts/*"

cache:
  yarn: true

branches:
  except:
  - codecov-config

before_install:
  - yarn global add lerna

install:
  - yarn bootstrap

script:
  - yarn lint
  - yarn flow-typed-install
  - yarn flow
  - yarn codecov
  - yarn build

before_deploy:
  - yarn build-storybook

deploy:
  provider: pages
  edge: true
  github_token: $GITHUB_TOKEN
  local_dir: storybook-static
  on:
    branch: master