if: tag IS blank

language: node_js

node_js:
  - "lts/*"

cache:
  yarn: true

before_install:
  - yarn global add lerna

install:
  - yarn bootstrap

script:
  - yarn lint
  - yarn flow-typed-install
  - yarn flow
  - yarn test -- --coverage
  - yarn build

before_deploy:
  - yarn build-storybook

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: storybook-static
  on:
    branch: master

after_script:
  - yarn codecov