enableScripts: false

packageExtensions:
  "@storybook/addon-docs@*":
    dependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/docs-tools@*":
    dependencies:
      react: "*"
      react-dom: "18.0.0"
  "@storybook/instrumenter@*":
    dependencies:
      react: "*"
      react-dom: "18.0.0"
  "@storybook/mdx1-csf@*":
    dependencies:
      "@babel/core": "*"
  debug@*:
    dependencies:
      supports-color: "*"
  eslint-config-react-app@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  node-fetch@*:
    dependencies:
      encoding: "*"
  stylelint-config-recommended-scss@*:
    dependencies:
      postcss: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.8.6.cjs
