enableScripts: false

packageExtensions:
  "@storybook/addon-docs@*":
    dependencies:
      "@babel/core": "*"
      regenerator-runtime: "*"
  "@storybook/addon-essentials@*":
    dependencies:
      babel-loader: "*"
  "@storybook/cli@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@storybook/codemod@*":
    dependencies:
      "@babel/core": "*"
      "@babel/preset-env": "*"
  "@storybook/docs-tools@*":
    dependencies:
      "react": "*"
      "react-dom": "*"
  "@storybook/mdx1-csf@*":
    dependencies:
      "@babel/core": "*"
  "@storybook/react@*":
    dependencies:
      jest: "*"
      jest-specific-snapshot: "4.0.0"
      require-from-string: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  eslint-config-react-app@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  node-fetch@*:
    dependencies:
      encoding: "*"
  react-cache@*:
    dependencies:
      scheduler: "*"
  stylelint-config-recommended-scss@*:
    dependencies:
      postcss: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
