enableScripts: false

packageExtensions:
  "@storybook/addon-docs@*":
    dependencies:
      regenerator-runtime: "*"
  "@storybook/addon-essentials@*":
    dependencies:
      babel-loader: "*"
  "@storybook/cli@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@storybook/codemod@*":
    dependencies:
      "@babel/core": "*"
      "@babel/preset-env": "*"
  "@storybook/mdx1-csf@*":
    dependencies:
      "@babel/core": "*"
  babel-loader@*:
    dependencies:
      webpack: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  eslint-config-react-app@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  node-fetch@*:
    dependencies:
      encoding: "*"
  raw-loader@*:
    dependencies:
      webpack: "*"
  react-cache@*:
    dependencies:
      scheduler: "*"
  source-map-loader@*:
    dependencies:
      webpack: "*"
  stylelint-config-recommended-scss@*:
    dependencies:
      postcss: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.0-rc.16.cjs
