name: Renovate
on:
  workflow_dispatch:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/10 * * * *' # Every 10 minutes

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5
        with:
          concurrent_skipping: always
          skip_after_successful_duplicate: false
          do_not_skip: '[]'
  renovate:
    needs: check
    if: needs.check.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: root
      DOCKER_USER_HOME: /home/ubuntu
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          app-id: ${{ secrets.BOT_APP_ID }}
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set Yarn global folder
        id: yarn_global_folder
        env:
          YARN_GLOBAL_FOLDER: ${{ runner.temp }}/.yarn/berry
        run: |
          echo "YARN_GLOBAL_FOLDER=$YARN_GLOBAL_FOLDER" >> .env
          echo "YARN_GLOBAL_FOLDER=$YARN_GLOBAL_FOLDER" >> $GITHUB_OUTPUT
        shell: bash
      - name: Setup Node.js environment
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 22.x
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Start Turbo Cache Server
        uses: rharkor/caching-for-turbo@a1c4079258ae08389be75b57d4d7a70f23c1c66d # v1.8
        with:
          cache-prefix: ${{ vars.TURBO_CACHE_PREFIX }}
      - name: Install dependencies
        run: yarn install
      - name: Build renovate config
        run: yarn run-script renovate.config.ts > renovate.config.json
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@abd08c7549b2a864af5df4a2e369c43f035a6a9d # v46.1.5
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_BASE_DIR: ${{ env.DOCKER_USER_HOME }}
          RENOVATE_PRINT_CONFIG: true
          LOG_LEVEL: debug
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        with:
          configurationFile: renovate.config.json
          token: ${{ steps.get_token.outputs.token }}
          docker-user: ${{ env.DOCKER_USER }}
          docker-volumes: |
            ${{ steps.yarn_global_folder.outputs.YARN_GLOBAL_FOLDER }}:${{ env.DOCKER_USER_HOME }}/.yarn/berry
          env-regex: "^(?:(RENOVATE_|YARN_)\\w+|LOG_LEVEL)$"
