name: Sync Lastest Changes

on:
  workflow_call:
    inputs:
      ref_name:
        type: string
        default: main
      squash:
        type: boolean
  workflow_dispatch:
    inputs:
      ref_name:
        type: string
        default: main
      squash:
        type: boolean

concurrency:
  group: sync-${{ inputs.ref_name}}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_VERBOSITY: ${{ vars.TURBO_VERBOSITY || 0 }}
      TURBO_ENV_MODE: ${{ vars.TURBO_ENV_MODE || 'strict' }}
      TURBO_TELEMETRY_DISABLED: 1
      YARN_CHECKSUM_BEHAVIOR: update
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          app-id: ${{ secrets.BOT_APP_ID }}
      - name: Get GitHub App User ID
        id: get_user_id
        env:
          GH_TOKEN: ${{ steps.get_token.outputs.token }}
        run: echo "user-id=$(gh api "/users/${{ steps.get_token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      - name: Configure git
        run: |
          git config --global user.name ${{ steps.get_token.outputs.app-slug }}[bot]
          git config --global user.email ${{ steps.get_user_id.outputs.user-id }}+${{ steps.get_token.outputs.app-slug }}[bot]@users.noreply.github.com
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          token: ${{ steps.get_token.outputs.token }}
          ref: ${{ inputs.ref_name }}
      - name: Set Yarn global folder
        env:
          YARN_GLOBAL_FOLDER: ${{ runner.temp }}/.yarn/berry
        run: echo "YARN_GLOBAL_FOLDER=$YARN_GLOBAL_FOLDER" >> .env
      - name: Setup Node.js environment
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 22.x
          cache: yarn
          cache-dependency-path: '**/yarn.lock'
      - name: Merge with base branch
        run: |
          git remote add base https://github.com/psychobolt/vite-storybook-boilerplate.git
          git fetch base main
          if [[ "${{ inputs.squash }}" == "true" ]]; then
            git merge base/main --allow-unrelated-histories --squash -X ours || true
          else
            git merge base/main --allow-unrelated-histories --no-commit --ff -X ours || true
          fi
      - name: Prune deleted files
        run: git status | grep 'deleted by us' | awk '{print $4}' | (xargs git rm || true)
      - name: Start Turbo Cache Server
        uses: rharkor/caching-for-turbo@a1c4079258ae08389be75b57d4d7a70f23c1c66d # v1.8
        with:
          cache-prefix: ${{ vars.TURBO_CACHE_PREFIX }}
      - name: Install dependencies
        run: |
          yarn install
          yarn bootstrap
      - name: Amend Merge
        run: git diff-index --quiet HEAD || (git add . && git commit --no-edit) || true
      - name: Update ${{ inputs.ref_name }} branch
        run: git push origin
